billing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),

    path('', views.home, name="home"), 
    path('tax-slab/', views.tax_slab_index, name="tax_slab_index"),
    path('tax-slab/add/', views.tax_slab_add, name="tax_slab_add"),
    path('tax-slab/edit/<str:tax_slab_id>/', views.tax_slab_edit, name="tax_slab_edit"),
    path('tax-slab/delete/<str:tax_slab_id>/', views.tax_slab_delete, name="tax_slab_delete"),

    path('service/', views.service_index, name="service_index"),
    path('service/add/', views.service_add, name="service_add"),
    path('service/edit/<str:service_id>/', views.service_edit, name="service_edit"),
    path('service/delete/<str:service_id>/', views.service_delete, name="service_delete"),

    path('customer/', views.customer_index, name="customer_index"),
    path('customer/add/', views.customer_add, name="customer_add"),
    path('customer/edit/<str:customer_id>/', views.customer_edit, name="customer_edit"),
    path('customer/delete/<str:customer_id>/', views.customer_delete, name="customer_delete"),

    path('firm/', views.firm_index, name="firm_index"),
    path('firm/add/', views.firm_add, name="firm_add"),
    path('firm/edit/<str:firm_id>/', views.firm_edit, name="firm_edit"),
    path('firm/delete/<str:firm_id>/', views.firm_delete, name="firm_delete"),

    path('invoice/', views.invoice_index, name="invoice_index"),
    path('invoice/create/', views.invoice_create, name="invoice_create"),
    path('invoice/add-item/<str:invoice_id>/', views.invoice_add_item, name="invoice_add_item"),
    path('invoice/delete-item/<str:invoice_item_id>/', views.invoice_item_delete, name="invoice_delete_item"),
    path('invoice/view/<str:invoice_id>/', views.invoice_view, name="invoice_view"),
    path('invoice/edit/<str:invoice_id>/', views.invoice_edit, name="invoice_edit"),
    path('invoice/delete/<str:invoice_id>/', views.invoice_delete, name="invoice_delete"),

]

mainapp/models.py
from django.db import models


# Create your models here.


class TaxSlab(models.Model):
    value = models.DecimalField(max_digits=4, decimal_places=2, default=0.00, blank=False, null=False)

    def __str__(self):
        return str(self.value) + " % "


class Service(models.Model):
    name = models.CharField(max_length=25, null=False, blank=False, unique=True)

    def __str__(self):
        return str(self.name)


class Firm(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, unique=True)
    address = models.TextField(max_length=300, null=False, blank=False)
    state = models.CharField(max_length=50, null=False, blank=False)
    mobile_number = models.CharField(max_length=25, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=True, default="")
    bank_ac_name = models.CharField(max_length=50, null=False, blank=True, default="")
    bank_name = models.CharField(max_length=50, null=False, blank=True, default="")
    bank_branch_address = models.TextField(max_length=300, null=False, blank=True, default="")
    bank_ac_number = models.CharField(max_length=30, null=False, blank=True, default="")
    bank_ifsc_code = models.CharField(max_length=30, null=False, blank=True, default="")
    gstin_number = models.CharField(max_length=30, null=False, blank=True, default="")
    footer_text = models.TextField(max_length=300, null=False, blank=True, default=" ")

    def __str__(self):
        return str(self.name)


class Customer(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, unique=True)
    address = models.TextField(max_length=300, null=False, blank=False)
    state = models.CharField(max_length=50, null=False, blank=False)
    mobile_number = models.CharField(max_length=25, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=True, default="")
    bank_ac_name = models.CharField(max_length=50, null=False, blank=True, default="")
    bank_name = models.CharField(max_length=50, null=False, blank=True, default="")
    bank_branch_address = models.TextField(max_length=300, null=False, blank=True, default="")
    bank_ac_number = models.CharField(max_length=30, null=False, blank=True, default="")
    bank_ifsc_code = models.CharField(max_length=30, null=False, blank=True, default="")
    gstin_number = models.CharField(max_length=30, null=False, blank=True, default="")

    def __str__(self):
        return str(self.name)


class Invoice(models.Model):
    firm = models.ForeignKey(Firm, on_delete=models.PROTECT, blank=False, null=False)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, blank=False, null=False)
    tax_slab = models.ForeignKey(TaxSlab, on_delete=models.PROTECT, blank=False, null=False)
    challan_nos = models.CharField(max_length=150, null=False, blank=True, default=" ")
    entry_time = models.DateTimeField(blank=False, null=False)
    item_description = models.CharField(max_length=200, null=False, blank=True, default=" ")
    sub_total = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=False, default=0)
    gst_amount = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=False, default=0)
    total_with_gst = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=False, default=0)

    def __str__(self):
        return str(self.id) + " | " + str(self.customer) + " | " + str(self.total_with_gst)


class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, blank=True, null=True)
    service = models.ForeignKey(Service, on_delete=models.PROTECT, blank=False, null=False)
    description = models.CharField(max_length=200, null=False, blank=True, default=" ")
    quantity = models.IntegerField(blank=False, null=False)
    rate_per_unit = models.DecimalField(max_digits=12, decimal_places=2, blank=False, null=False, default=0)
    amount = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=False, default=0)

mainapp/forms.py
from django.forms import ModelForm
from django import forms
from mainapp.models import *
from bootstrap_datepicker_plus import DateTimePickerInput


class TaxSlabForm(ModelForm):
    class Meta:
        model = TaxSlab
        fields = '__all__'


class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = '__all__'


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'


class FirmForm(ModelForm):
    class Meta:
        model = Firm
        fields = '__all__'


class InvoiceForm(ModelForm):
    class Meta:
        model = Invoice
        fields = '__all__'
        widgets = {
            'entry_time': DateTimePickerInput(),  # default date-format %m/%d/%Y will be used
        }


class InvoiceItemForm(ModelForm):
    class Meta:
        model = InvoiceItem
        fields = '__all__'

mainapp/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
from mainapp.decorators import unauthenticated_user
from mainapp.forms import TaxSlabForm, ServiceForm, CustomerForm, FirmForm, InvoiceForm, InvoiceItemForm
from mainapp.models import TaxSlab, Service, Customer, Firm, Invoice, InvoiceItem
from indicnum2words.num_to_word import num_to_word


@unauthenticated_user
def loginPage(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username OR Password Invalid.')
    return render(request, 'mainapp/login.html')


@login_required(login_url='login')
def logoutUser(request):
    logout(request)
    return redirect('login')


@login_required(login_url='login')
def home(request):
    context = {}
    return render(request, 'mainapp/home.html', context)


@login_required(login_url='login')
def tax_slab_index(request):
    tax_slabs = TaxSlab.objects.all()
    context = {'tax_slabs': tax_slabs}
    return render(request, 'mainapp/TaxSlab/index.html', context)


@login_required(login_url='login')
def tax_slab_delete(request, tax_slab_id):
    try:
        tax_slab = TaxSlab.objects.get(id=tax_slab_id)
        tax_slab.delete()
        messages.success(request, "Tax Slab deleted Successfully")
    except:
        messages.warning(request, "Unable to delete Tax Slab")
    return redirect('tax_slab_index')


@login_required(login_url='login')
def tax_slab_add(request):
    form = TaxSlabForm()
    if request.method == 'POST':
        form = TaxSlabForm(request.POST)
        if form.is_valid():
            form.save()
            form = TaxSlabForm()
            messages.success(request, "Tax Slab added Successfully")
        else:
            error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
            messages.warning(request, "Unable to add Tax Slab, " + error_string)
    context = {'form': form}
    return render(request, 'mainapp/TaxSlab/add.html', context)


@login_required(login_url='login')
def tax_slab_edit(request, tax_slab_id):
    tax_slab = TaxSlab.objects.get(id=tax_slab_id)
    form = TaxSlabForm(instance=tax_slab)
    if request.method == 'POST':
        form = TaxSlabForm(request.POST, instance=tax_slab)
        if form.is_valid():
            form.save()
            form = TaxSlabForm()
            messages.success(request, "Tax Slab updated Successfully")
            return redirect('tax_slab_index')
        else:
            error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
            messages.warning(request, "Unable to update Tax Slab, " + error_string)
    context = {'form': form}
    return render(request, 'mainapp/TaxSlab/add.html', context)


@login_required(login_url='login')
def service_index(request):
    services = Service.objects.all()
    context = {'services': services}
    return render(request, 'mainapp/Service/index.html', context)


@login_required(login_url='login')
def service_add(request):
    form = ServiceForm()
    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            form.save()
            form = ServiceForm()
            messages.success(request, "Service added Successfully")
        else:
            error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
            messages.warning(request, "Unable to add Service, " + error_string)
    context = {'form': form}
    return render(request, 'mainapp/Service/add.html', context)


@login_required(login_url='login')
def service_edit(request, service_id):
    service = Service.objects.get(id=service_id)
    form = ServiceForm(instance=service)
    if request.method == 'POST':
        form = ServiceForm(request.POST, instance=service)
        if form.is_valid():
            form.save()
            messages.success(request, "Service added Successfully")
            return redirect('service_index')
        else:
            error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
            messages.warning(request, "Unable to add Service, " + error_string)
    context = {'form': form}
    return render(request, 'mainapp/Service/add.html', context)


@login_required(login_url='login')
def service_delete(request, service_id):
    try:
        service = Service.objects.get(id=service_id)
        service.delete()
        messages.success(request, "Service deleted Successfully")
    except:
        messages.warning(request, "Unable to delete Service")
    return redirect('service_index')


@login_required(login_url='login')
def customer_index(request):
    customers = Customer.objects.all()
    context = {'customers': customers}
    return render(request, 'mainapp/Customer/index.html', context)


@login_required(login_url='login')
def customer_add(request):
    form = CustomerForm()
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            form = CustomerForm()
            messages.success(request, "Customer added Successfully")
        else:
            error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
            messages.warning(request, "Unable to add Customer, " + error_string)
    context = {'form': form}
    return render(request, 'mainapp/Customer/add.html', context)


@login_required(login_url='login')
def customer_edit(request, customer_id):
    customer = Customer.objects.get(id=customer_id)
    form = CustomerForm(instance=customer)
    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            messages.success(request, "Customer edited Successfully")
            return redirect('customer_index')
        else:
            error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
            messages.warning(request, "Unable to edit Customer, " + error_string)
    context = {'form': form}
    return render(request, 'mainapp/Customer/add.html', context)


@login_required(login_url='login')
def customer_delete(request, customer_id):
    try:
        customer = Customer.objects.get(id=customer_id)
        customer.delete()
        messages.success(request, "Customer deleted Successfully")
    except:
        messages.warning(request, "Unable to delete Customer")
    return redirect('customer_index')


@login_required(login_url='login')
def firm_index(request):
    firms = Firm.objects.all()
    context = {'firms': firms}
    return render(request, 'mainapp/Firm/index.html', context)


@login_required(login_url='login')
def firm_add(request):
    form = FirmForm()
    if request.method == 'POST':
        form = FirmForm(request.POST)
        if form.is_valid():
            form.save()
            form = FirmForm()
            messages.success(request, "Firm added Successfully")
        else:
            error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
            messages.warning(request, "Unable to add Firm, " + error_string)
    context = {'form': form}
    return render(request, 'mainapp/Firm/add.html', context)


@login_required(login_url='login')
def firm_edit(request, firm_id):
    firm = Firm.objects.get(id=firm_id)
    form = FirmForm(instance=firm)
    if request.method == 'POST':
        form = FirmForm(request.POST, instance=firm)
        if form.is_valid():
            form.save()
            messages.success(request, "Firm edited Successfully")
            return redirect('firm_index')
        else:
            error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
            messages.warning(request, "Unable to edit Firm, " + error_string)
    context = {'form': form}
    return render(request, 'mainapp/Firm/add.html', context)


@login_required(login_url='login')
def firm_delete(request, firm_id):
    try:
        firm = Firm.objects.get(id=firm_id)
        firm.delete()
        messages.success(request, "firm deleted Successfully")
    except:
        messages.warning(request, "Unable to delete firm")
    return redirect('firm_index')


# support function not view
def invoice_calc_total(invoice_id):
    invoice = Invoice.objects.get(id=invoice_id)
    sub_total = InvoiceItem.objects.filter(invoice=invoice).aggregate(Sum('amount'))['amount__sum']
    gst_slab = invoice.tax_slab.value
    gst_amount = sub_total * (gst_slab / 100)
    total_with_gst = sub_total + gst_amount
    invoice.sub_total = sub_total
    invoice.gst_amount = gst_amount
    invoice.total_with_gst = total_with_gst
    invoice.save()


@login_required(login_url='login')
def invoice_create(request):
    form = InvoiceForm()
    if request.method == 'POST':
        form = InvoiceForm(request.POST)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.save()
            messages.success(request, "Invoice created successfully, now add items")
            return redirect('invoice_add_item', entry.id)
        else:
            error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
            messages.warning(request, "Unable to create Invoice, " + error_string)
    context = {'form': form}
    return render(request, 'mainapp/Invoice/create.html', context)


@login_required(login_url='login')

mainapp/templates/mainapp/Invoice/add_item.html
{% extends 'mainapp/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Create Invoice</h5>
                    <span class="text-muted">Create new invoice</span>
                    <div class="card-header-right">
                        <ul class="list-unstyled card-option">
                            <li><i class="feather icon-maximize full-card"></i></li>
                            <li><i class="feather icon-minus minimize-card"></i></li>
                        </ul>
                    </div>
                </div>
                <div class="card-block">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                {{ form.service|attr:"tabindex:1"|as_crispy_field }}
                                {{ form.description|attr:"tabindex:2"|as_crispy_field }}
                                {{ form.quantity|attr:"tabindex:3"|as_crispy_field }}
                                {{ form.rate_per_unit|attr:"tabindex:4"|as_crispy_field }}
                                Total Amount : <span id="total_amount">0</span>
                            </div>
                            <div class="col-md-8">
                                <div class="card-block">
                                    <div class="dt-responsive table-responsive">
                                        <table id="myTable" class="table w-100 mx-0">
                                            <thead>
                                            <tr>
                                                <th>Sr. No.</th>
                                                <th>Description</th>
                                                <th>Qty</th>
                                                <th>Rate/Unit</th>
                                                <th>Amount</th>
                                                <th class="nosort">Actions</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in invoice_items %}
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td>{{ item.service }} {{ item.description }}</td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.rate_per_unit }}</td>
                                                    <td>{{ item.amount }}</td>
                                                    <td>
                                                        <div class="table-actions text-center">
                                                            {#                                                            <a href="{% url 'service_edit' service.id %}"> <i#}
                                                            {#                                                                    class="feather icon-edit text-success"></i></a>#}
                                                            <a href="{% url 'invoice_delete_item' item.id %}"
                                                               onclick="return confirm('Are you sure you want to delete this item?');"><i
                                                                    class="feather icon-trash-2 text-danger"></i></a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>

                                </div>
                            </div>
                            <div class="col-12 pt-1">
                                <input class="btn btn-success mt-4" type="submit" value="Add Item"
                                       tabindex="2">
                                <a class="btn btn-primary mt-4" href="{% url 'invoice_index' %}"
                                   accesskey="b">Finish</a>
                            </div>
                            <div class="col-sm-12">
                                {{ form.errors }}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script_end %}
    <script>
        $(document).ready(function () {
            $('#myTable').dataTable({responsive: true});

            function calculate() {
                console.log('fun triggered')
                let quantity = Number($('#id_quantity').val())
                let rate_per_unit = Number($('#id_rate_per_unit').val())
                let total_amount = rate_per_unit * quantity
                $('#total_amount').html(total_amount)
            }

            $("#id_quantity,#id_rate_per_unit").change(function () {
                calculate()
            });
        });
    </script>
{% endblock %}

mainapp/templates/mainapp/Invoice/create.html
{% extends 'mainapp/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Create Invoice</h5>
                    <span class="text-muted">Create new invoice</span>
                    <div class="card-header-right">
                        <ul class="list-unstyled card-option">
                            <li><i class="feather icon-maximize full-card"></i></li>
                            <li><i class="feather icon-minus minimize-card"></i></li>
                        </ul>
                    </div>
                </div>
                <div class="card-block">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                {{ form.firm|attr:"tabindex:1"|as_crispy_field }}
                                {{ form.customer|attr:"tabindex:1"|as_crispy_field }}
                                {{ form.tax_slab|attr:"tabindex:1"|as_crispy_field }}
                            </div>
                            <div class="col-md-6">
                                {{ form.challan_nos|attr:"tabindex:1"|as_crispy_field }}
                                {{ form.item_description|attr:"tabindex:1"|as_crispy_field }}
                                {{ form.entry_time|attr:"tabindex:1"|as_crispy_field }}
                            </div>
                            <div class="col-12 pt-1">
                                <input class="btn btn-success mt-4" type="submit" value="Save -> Add Items"
                                       tabindex="2">
                                <a class="btn btn-secondary mt-4" href="{% url 'invoice_index' %}"
                                   accesskey="b"><u>B</u>ack</a>
                            </div>
                            <div class="col-sm-12">
                                {{ form.errors }}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script_end %}
    {{ form.media }}
{% endblock %}

mainapp/templates/mainapp/Invoice/view.html
{% load mathfilters %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Invoice</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-12 mt-4">
            <h2>{{ invoice.firm.name|upper }}</h2>
            {{ invoice.firm.address }}<br/>
            Contact No.: {{ invoice.firm.mobile_number }}<br>
            Email: {{ invoice.firm.email }}<br>
            GSTIN: {{ invoice.firm.gstin_number }}<br>
            State: {{ invoice.firm.state }}<br>
        </div>
        <div class="col-12 text-center my-5"><h4>TAX INVOICE</h4></div>
        <div class="col-6">
            <strong>Bill To:</strong><br>
            <strong>{{ invoice.customer.name }}</strong><br>
            {{ invoice.customer.address }}<br>
            GSTIN No.: {{ invoice.customer.gstin_number }}<br>
            Contact No.: {{ invoice.customer.mobile_number }}<br>
            State: {{ invoice.customer.state }}<br>
            <br>
            <br>
        </div>
        <div class="col-6 text-right">
            Place of Supply: {{ invoice.firm.state }} <br>
            <strong>Invoice No.: {{ invoice.entry_time|date:'Y/m' }}/{{ invoice.id }}</strong><br>
            <strong>Challan No(s): {{ invoice.challan_nos }}</strong><br>
            <strong>Date: {{ invoice.entry_time }}</strong><br>
        </div>
        <div class="col-12 my-2">
            <strong>Item Description: </strong> {{ invoice.item_description }}<br>
        </div>
        <div class="col-12 my-3">
            <table class="table">
                <thead class="">
                <tr>
                    <th scope="col">S.NO.</th>
                    <th scope="col">Description</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Rate/Unit</th>
                    <th scope="col">Amount</th>
                </tr>
                </thead>
                <tbody>
                {% for item in invoice.invoiceitem_set.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ item.service }} {{ item.description }}</td>
                        <td>{{ item.quantity }} Units</td>
                        <td> ₹ {{ item.rate_per_unit }}</td>
                        <td> ₹ {{ item.amount }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <strong>OUR BANK DETAILS</strong>
            <div>
                A/C Name: {{ invoice.firm.bank_ac_name }} <br>
                A/C NO.: {{ invoice.firm.bank_ac_number }} <br>
                BANK: {{ invoice.firm.bank_name }} <br>
                IFSC: {{ invoice.firm.bank_ifsc_code }} <br>
            </div>
            <div class="mt-4">
                <strong>Thank you for your business.</strong>
            </div>

        </div>
        <div class="col-5 offset-1">
            <div class="row">
                {% if invoice.tax_slab.value > 0 %}
                    <div class="col-6">
                        Sub Total
                    </div>
                    <div class="col-6 text-right">
                        ₹ {{ invoice.sub_total }}
                    </div>
                    <div class="col-6">
                        SGST@{{ invoice.tax_slab.value|div:2 }}%
                    </div>
                    <div class="col-6 text-right">
                        ₹ {{ invoice.gst_amount|div:2 }}
                    </div>
                    <div class="col-6">
                        CGST@{{ invoice.tax_slab.value|div:2 }}%
                    </div>
                    <div class="col-6 text-right">
                        ₹ {{ invoice.gst_amount|div:2 }}
                    </div>
                {% endif %}

                <div class="col-6 ">
                    <strong>Total Amount</strong>
                </div>
                <div class="col-6 text-right">
                    <strong> ₹ {{ invoice.total_with_gst }}</strong>
                </div>
                <div class="col-6 ">
                    <strong>Net Amount</strong>
                </div>
                <div class="col-6 text-right">
                    <strong> ₹ {{ total_in_num }}</strong>
                </div>
                <div class="col-12">
                    <div class="mt-4">
                        <strong>INVOICE AMOUNT IN WORDS</strong>
                    </div>
                    <div>
                        <strong>{{ total_amount_in_words_en|title }} Rupees Only</strong>
                    </div>
                    <div>
                        <strong>{{ total_amount_in_words_hi }} रुपए मात्र</strong>
                    </div>
                </div>
            </div>
            <div class="col-12 mt-5 text-center">
                <strong>For, {{ invoice.firm.name|upper }}</strong>
                <br><br><br><br><br>
                <strong>Authorized Signatory</strong>
            </div>
        </div>
        <div class="col-12 text-center">
            <br><br><br>
            <strong>{{ invoice.firm.footer_text|linebreaks }}</strong>
        </div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>